### PR TITLE
fix: replace crypto.randomUUID to allow insecure environments (fix #9…

### LINKED ISSUE #9338: Browser-Mode fails in insecure environment
### Describe the bug

When using vitest with a server configured to not use localhost, but any other domain without https, vitest fails with the exception "TypeError: crypto.randomUUID is not a function" thrown in wrapModule
https://github.com/vitest-dev/vitest/blob/7b10ab4cd7d23d3c520fd1f6956ce99108f70a04/packages/browser/src/client/public/esm-client-injector.js#L12

The function crypto.randomUUID is not available in insecure environments https://developer.mozilla.org/de/docs/Web/API/Crypto/randomUUID
In CI setups with a remote-selenium-hub it is very useful to spin up vitest-server accessable through the machines hostname, without the need to configure tls.

I consider this a regression, since a similar thing got fixed in #6079

### Reproduction

https://github.com/plusgut/vitest-minimal-reproduction-randomuui/commit/02a2398df11d521405b9ce0754a2b9d8369d6684

### System Info

```shell
System:
    OS: Linux 6.18 cpe:/o:nixos:nixos:26.05 26.05 (Yarara)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 17.72 GB / 27.23 GB
    Container: Yes
    Shell: 4.2.1 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 22.21.1 - /nix/store/l85fis49agvp5q1ild1rfh4rrgmn92sr-nodejs-22.21.1/bin/node
    npm: 10.9.4 - /nix/store/l85fis49agvp5q1ild1rfh4rrgmn92sr-nodejs-22.21.1/bin/npm
  Browsers:
    Chromium: 143.0.7499.40
    Firefox: 145.0.2
    Firefox Developer Edition: 145.0.2
  npmPackages:
    @vitest/browser-preview: ^4.0.16 => 4.0.16 
    @vitest/ui: latest => 4.0.16 
    vite: latest => 7.3.0 
    vitest: latest => 4.0.16
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by plusgut**
fixes #9338

### Description

crypto.randomUUID is not available in the browser in case it gets executed in an insecure environment Math.random() should suffice for mocking

Resolves #issue-number

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.
- [x] Please check [Allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to make review process faster. Note that this option is not available for repositories that are owned by Github organizations.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

### CODE REVIEW

**Comment by userquin** [comment]
Check #6079 maybe we can just reuse the tested id using replaceAll in the vite plugin

**Comment by sheremet-va** [comment]
> Check #6079 maybe we can just reuse the tested id using replaceAll in the vite plugin

We just need a random string, it has nothing to do with the tester id

**Comment by plusgut** [comment]
> > Check #6079 maybe we can just reuse the tested id using replaceAll in the vite plugin
> 
> We just need a random string, it has nothing to do with the tester id

@sheremet-va So good ol Math.random is fine by you, if it is in a tenplate literal?

I undrafted the pr now, if you want something to be changed let me know. Do you think a test-case for this would be beneficial?

**Comment by sheremet-va** [comment]
> I undrafted the pr now, if you want something to be changed let me know. Do you think a test-case for this would be beneficial?

Feel free to add a test case. I think we only have one instance where we run with http:
https://github.com/vitest-dev/vitest/blob/f9271a0811147d4ca71488ebd4fc442733d014e5/test/browser/specs/server-url.test.ts#L8

**Comment by plusgut** [comment]
@sheremet-va setting it to http is actually no enough for it to be considered insecure. https://www.w3.org/TR/secure-contexts/#is-origin-trustworthy states that 127.0.0.1 and localhost are always considered trustworthy, no matter if http or https.

Thats why i used the hostname of the machine, but sadly that doesnt seem to work with mac-os. I guess mac-os doesnt automatically resolve it.

I now looked up if there is some browser-capability to set it into insecure-context mode, but that doesn`t seem to exist. I only was able to find the opposite in chrome "--unsafely-treat-insecure-origin-as-secure".

I'm not really sure how to proceed from here, what do you think of skipping the tests in case the os.platform is not linux or windows?
Alternatively i could go over os.networkInterfaces().eth0 and see if that works inside the vm`s.

What do you think would be the best approach without being to brittle?

**Comment by sheremet-va** [comment]
I think running the test on a single platform that allows an easy check is fine.

**Comment by plusgut** [comment]
@sheremet-va that sounds very reasonable to me.

I believe everything should be looking good now, let me know if everything is to your liking or if I should change something.

There are a couple of failing thing in CI, but i believe they are unrelated to my changes. Could you verify that?

File: test/browser/specs/insecure-context.test.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import os from 'node:os'
+import { expect, test } from 'vitest'
+import { instances, runBrowserTests } from './utils'
+
+test('server-host check dynamic import at insecure context', async () => {
```
Comment (sheremet-va) [inline test/browser/specs/insecure-context.test.ts]:
```suggestion
test.runIf(os.platform() === 'linux')('server-host check dynamic import at insecure context', async () => {
```
