### ISSUE TITLE
@types/chai conflict with @vitest/expect/dist/chai.d.cts

### ISSUE THREAD

**Issue by antoniosZ** [vitest-dev/vitest#4688]
### Describe the bug

since [v1.0.0-beta.1](https://github.com/vitest-dev/vitest/releases/tag/v1.0.0-beta.1)
https://github.com/vitest-dev/vitest/commit/5996c8c0

I get the following:

```
../../node_modules/@types/chai/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: Message, ObjectProperty, ChaiPlugin, AssertionArgs, Operator, OperatorComparable, AssertionError, chai

1 declare namespace Chai {
  ~~~~~~~

  ../../node_modules/vitest/node_modules/@vitest/expect/dist/chai.d.cts:16:1
    16 declare namespace Chai {
       ~~~~~~~
    Conflicts are in this file.

../../node_modules/vitest/node_modules/@vitest/expect/dist/chai.d.cts:16:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: Message, ObjectProperty, ChaiPlugin, AssertionArgs, Operator, OperatorComparable, AssertionError, chai

16 declare namespace Chai {
   ~~~~~~~

  ../../node_modules/@types/chai/index.d.ts:1:1
    1 declare namespace Chai {
      ~~~~~~~
    Conflicts are in this file.


Found 2 errors in 2 files.
```

In case it matters, this is an NPM workspace project.
If I delete the file `node_modules/vitest/node_modules/@vitest/expect/dist/chai.d.cts` everything compiles successfully like before the upgrade to  [v1.0.0-beta.1](https://github.com/vitest-dev/vitest/releases/tag/v1.0.0-beta.1).

### Reproduction

install and try to compile without skipLibCheck: true in tsconfig

### System Info

```shell
System:
    OS: macOS 13.6.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.2.1 - ~/my-project/node_modules/.bin/npm
  npmPackages:
    @vitest/coverage-v8: ^1.0.1 => 1.0.1 
    vite: ^5.0.6 => 5.0.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Why do you have `@types/chai` installed?

**Comment by antoniosZ** [comment]
@sheremet-va I removed the `@storybook/test` package and I still get the same conflict with the following
```
$npm list @types/chai
@testing-library/jest-dom@6.1.5
    └─┬ vitest@0.34.6
      ├─┬ @types/chai-subset@1.3.3
      │ └── @types/chai@4.3.5 deduped
      └── @types/chai@4.3.5
```

**Comment by antoniosZ** [comment]
https://github.com/testing-library/jest-dom/blob/main/package.json#L104

seems like to resolve this, everyone else has to remove their `@types/chai` dependency or vitest has to remove their bundled typings of chai...

**Comment by sheremet-va** [comment]
> https://github.com/testing-library/jest-dom/blob/main/package.json#L104
> 
> 
> 
> seems like to resolve this, everyone else has to remove their `@types/chai` dependency or vitest has to remove their bundled typings of chai...

This is a dev dependency, it's not installed. jest-dom has a peer dependency of Vitest which should just reuse existing one. Try deleting a lockfile and installing everything again.

**Comment by antoniosZ** [comment]
@sheremet-va I just created a minimal reproduction...
https://stackblitz.com/edit/vitest-dev-vitest-nowys5?file=package.json
if you run in the terminal `tsc` you will see the conflict...

`@storybook/test` for sure creates the conflict

**Comment by antoniosZ** [comment]
the way I see this, any other package that has `@types/chai` as a dependency/devDependency, will cause a conflict with vitest, just because vitest embeds the chai typings. But I could be wrong in my understanding here.

**Comment by majo44** [comment]
Hi, we have also this issue.

We have huge monorepo (~400 packages/rush/pnpm), we are on the mocha/chai/sinon, and we made a try to migrate package by package to vitests. In general tests runs well, but compilation (type checking) on packages where we are using the vitest fails with:

```
../../../../common/temp/node_modules/.pnpm/@types+chai@4.3.9/node_modules/@types/chai/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: Message, ObjectProperty, ChaiPlugin, AssertionArgs, Operator, OperatorComparable, AssertionError, chai

1 declare namespace Chai {
  ~~~~~~~

  ../../../../common/temp/node_modules/.pnpm/@vitest+expect@1.1.0/node_modules/@vitest/expect/dist/chai.d.cts:16:1
    16 declare namespace Chai {
       ~~~~~~~
    Conflicts are in this file.

../../../../common/temp/node_modules/.pnpm/@vitest+expect@1.1.0/node_modules/@vitest/expect/dist/chai.d.cts:16:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: Message, ObjectProperty, ChaiPlugin, AssertionArgs, Operator, OperatorComparable, AssertionError, chai

16 declare namespace Chai {
   ~~~~~~~

  ../../../../common/temp/node_modules/.pnpm/@types+chai@4.3.9/node_modules/@types/chai/index.d.ts:1:1
    1 declare namespace Chai {
      ~~~~~~~
    Conflicts are in this file.


Found 2 errors in 2 files.

Errors  Files
     1  ../../../../common/temp/node_modules/.pnpm/@types+chai@4.3.9/node_modules/@types/chai/index.d.ts:1
     1  ../../../../common/temp/node_modules/.pnpm/@vitest+expect@1.1.0/node_modules/@vitest/expect/dist/chai.d.cts:16

```

The package itself is not depends on the `@types/chai`, but probably somewhere deep in the tree we (or 3partpy dep or dev dep) has such dependency/devDependecy, so it is installed in the tree, but .... funny is that the `vitests` is causing of loading of `@types/chai`, during the compilation: 

tsc --explainFiles says:
 
```
../../../../common/temp/node_modules/.pnpm/@types+chai@4.3.9/node_modules/@types/chai/index.d.ts
  Imported via 'chai' from file '../../../../common/temp/node_modules/.pnpm/vitest@1.1.0_@types+node@20.10.3/node_modules/vitest/dist/reporters-O4LBziQ_.d.ts' with packageId '@types/chai/index.d.ts@4.3.9'
  Imported via 'chai' from file '../../../../common/temp/node_modules/.pnpm/vitest@1.1.0_@types+node@20.10.3/node_modules/vitest/dist/index.d.ts' with packageId '@types/chai/index.d.ts@4.3.9'
```

In vitest 0.34 there was no such problem as vitest used the `@types/chai` instead of re-declare it internally.

**Comment by qraynaud** [comment]
Did someone find a workaround for this? This is very cumbersome…

**Comment by qraynaud** [comment]
Okay, I just found that adding `skipLibCheck: true` to the `tsconfig.json/compilerOptions` is doing the trick.

**Comment by kasperpeulen** [comment]
Trying to fix this in the next patch release of `@storybook/test`.

**Comment by Abdillah** [comment]
This seems to be Vitest issue.

Chai is obviously should not be included along with user facing `vitest` type. If Vitest has resemblance with Chai, it should be hidden.

**Comment by danielrentz** [comment]
I see a similar problem after upgrading vitest from 2.0.4 to 2.0.5

Without having `@types/chai` installed, I see
```txt
node_modules/vitest/dist/chunks/reporters.C_zwCd4j.d.ts:17:23 - error TS7016: Could not find a declaration file for module 'chai'. '.../node_modules/chai/chai.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/chai` if it exists or add a new declaration (.d.ts) file containing `declare module 'chai';`

17 import * as chai from 'chai';
                         ~~~~~~
Found 1 error in node_modules/vitest/dist/chunks/reporters.C_zwCd4j.d.ts:17
```

After installing `@types/chai` as suggested, I see
```txt
node_modules/@types/chai/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: Message, ObjectProperty, ChaiPlugin, AssertionArgs, Operator, OperatorComparable, AssertionError, chai

1 declare namespace Chai {
  ~~~~~~~

  node_modules/@vitest/expect/dist/chai.d.cts:16:1
    16 declare namespace Chai {
       ~~~~~~~
    Conflicts are in this file.

node_modules/@vitest/expect/dist/chai.d.cts:16:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: Message, ObjectProperty, ChaiPlugin, AssertionArgs, Operator, OperatorComparable, AssertionError, chai

16 declare namespace Chai {
   ~~~~~~~

  node_modules/@types/chai/index.d.ts:1:1
    1 declare namespace Chai {
      ~~~~~~~
    Conflicts are in this file.

Found 2 errors in 2 files.

Errors  Files
     1  node_modules/@types/chai/index.d.ts:1
     1  node_modules/@vitest/expect/dist/chai.d.cts:16
```

**Comment by Jym77** [comment]
Running into this too.
My use case is that I try to build integrations of my library with various test frameworks (so that end-user can more easily use it).

So, I have a monorepo [`alfa-integrations`](https://github.com/Siteimprove/alfa-integrations) where the existing package `alfa-chai` is importing Chai and its types. I'm trying to create an `alfa-vitest` package, importing Vitest. But every dependency in a monorepo is hosted in the root `node_modules` and somehow just having `vitest` and `@types/chai` there causes this problem.

**Comment by tassoevan** [comment]
Seeing it happen in a codebase with `@storybook/test` (depends on `@vitest/expect`) and `@types/chai`. It broke all `assert.isDefined()` calls as the function went from being an assertion function to a void-returning function.

**Comment by alecgibson** [comment]
This is also a problem if you try to use any `chai` plugins with `vitest` (we're also trying to migrate from `mocha`/`sinon`/`chai`:

```ts
import {chai} from 'vitest';
import chaiDom from 'chai-dom';
import chaiAsPromised from 'chai-as-promised';

chai.use(chaiDom);
chai.use(chaiAsPromised);
```

```sh
❯ npm list @types/chai
@my-project
├─┬ @types/chai-as-promised@8.0.1
│ └── @types/chai@5.0.1 deduped
└─┬ @types/chai-dom@1.11.3
  └── @types/chai@5.0.1 deduped
```

I don't think it's particularly strange that a `chai` plugin would include `@types/chai`.

Going to see if I can work around this by hand-rolling the types for the plugins, but it's not a great consumer experience.

**Comment by alecgibson** [comment]
I'm probably missing something, but can't `vitest` *also* just depend on `@types/chai` and let `npm` do its thing?

**Comment by alecgibson** [comment]
Okay one hack around this if you don't want `@vitest/expect`'s augmented `chai` types (ie if you're migrating from vanilla `chai` or want full control over your own `chai` plugins) is to tweak the shipped type definitions with a hideous `tsconfig.json` hack:

```json
{
  "compilerOptions": {
    "paths": {
      "@vitest/expect": ["./typings/vitest-expect.d.ts"],
    }
  }
}
```

Where `vitest-expect.d.ts` looks like this:

```ts
export * from '@vitest/expect/dist/index';
```

Which is basically the same as the [shipped type definition](https://github.com/vitest-dev/vitest/blob/96a746261b439c6546b12a03ac002f18a37419c9/packages/expect/index.d.ts), without the augmented `chai` import.

**Comment by hi-ogawa** [comment]
> I'm probably missing something, but can't `vitest` _also_ just depend on `@types/chai` and let `npm` do its thing?

@alecgibson One reason I'm aware of is because `@types/chai` injects global typing `Object.should`. We have this patched out and copied to `@vitest/expect/dist/chai.d.cts`. This isn't really ideal, but I guess this approach is chosen as a trade off. If you have any other ideas, please feel free to suggest 🙏 

https://github.com/vitest-dev/vitest/blob/e2c570b687316d636fc257a7011191667f0c765a/patches/%40types__chai%404.3.6.patch#L9-L14

I think your workaround of directly grabbing `@vitest/expect/dist/index` seems nice. Thanks for sharing 👍

**Comment by alecgibson** [comment]
@hi-ogawa while I agree mutating the global `Object` is horrible, I'm not (personally) sure that patching the library like this is the "correct" approach, for exactly the above reasons in this issue.

I think I'd expect one of the following:

- Just accept that patching `Object` was a design decision made with `chai`. If you don't agree with upstream decisions, 
don't use `chai` and use something else instead; or...
- Fork `chai` "properly" instead of this patch. Then you can re-release it under your own namespace `@vitest/chai` which won't clash with existing type definitions. Comes with the downside that existing plugin types won't work, but that's already the case anyway and this way you wouldn't break existing types

Obviously I'm not a maintainer/contributor on this library and wasn't privy to any of these design decisions (so what do I know), but that's what I personally would have done I think.

I guess if you wanted to make this a `DefinitelyTyped` problem (which it also sort of is), then I'd maybe raise a PR to drop this global augmentation from `@types/chai`, and move this augmentation into the namespace [`chai/register-should`](https://www.chaijs.com/guide/styles/#using-should-in-es2015) or something for clients to opt in to these types.

**Comment by alecgibson** [comment]
@hi-ogawa I got the upstream type fix merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72101
