### ISSUE TITLE
vi.mock importOriginal causes ERR_MODULE_NOT_FOUND with &v=<hash> suffix appended to path in 4.1.0

### ISSUE THREAD

**Issue by csvan** [vitest-dev/vitest#9886]
## Bug Report

**Vitest version:** 4.1.0
**Regression from:** 4.0.18 (works correctly)

### Description

In Vitest 4.1.0, calling `vi.mock` with `importOriginal` (or `vi.importActual`) on packages listed in `test.server.deps.inline` or `test.deps.optimizer.client.include` causes `ERR_MODULE_NOT_FOUND` at runtime. The module evaluator appends `&v=<hash>` directly to the resolved file path, producing a path that does not exist on disk.

This is a regression — the same configuration works correctly on 4.0.18.

### Reproduction

```ts
// vitest.config.ts
test: {
  server: {
    deps: {
      inline: [/@customer-connect\/hooks-web/],
    },
  },
}
```

```ts
// vitest.setup.ts
vi.mock('@customer-connect/hooks-web', async (importOriginal) => ({
  ...(await importOriginal()),
  useCurrentSession: vi.fn(() => ({ auth: { accessToken: 'token' } })),
}));
```

### Error

```
Error: Cannot find module '/node_modules/@customer-connect/hooks-web/esm/index.js&v=a0b441fd'
  ERR_MODULE_NOT_FOUND
```

The `&v=<hash>` suffix is appended to the literal file path by the module evaluator, making it unresolvable on disk.

The same error occurs when the package is in `test.deps.optimizer.client.include` instead — the pre-bundled chunk path gets the suffix appended:

```
Error: Cannot find module '/node_modules/.vite/vitest/.../deps/@customer-connect_hooks-web.js&v=8f02ed9a'
```

### Expected behavior

`importOriginal` / `vi.importActual` should resolve the module correctly regardless of whether it is listed in `server.deps.inline` or `optimizer.client.include`, as it did in 4.0.x.

### Workaround

Pinning to `~4.0.0` via `overrides` in `package.json` resolves the issue.

**Comment by csvan** [comment]
Closing to refile with a cleaner reproduction example.
