### ISSUE TITLE
Browser-Mode fails in insecure environment

### ISSUE THREAD

**Issue by plusgut** [vitest-dev/vitest#9338]
### Describe the bug

When using vitest with a server configured to not use localhost, but any other domain without https, vitest fails with the exception "TypeError: crypto.randomUUID is not a function" thrown in wrapModule
https://github.com/vitest-dev/vitest/blob/7b10ab4cd7d23d3c520fd1f6956ce99108f70a04/packages/browser/src/client/public/esm-client-injector.js#L12

The function crypto.randomUUID is not available in insecure environments https://developer.mozilla.org/de/docs/Web/API/Crypto/randomUUID
In CI setups with a remote-selenium-hub it is very useful to spin up vitest-server accessable through the machines hostname, without the need to configure tls.

I consider this a regression, since a similar thing got fixed in #6079

### Reproduction

https://github.com/plusgut/vitest-minimal-reproduction-randomuui/commit/02a2398df11d521405b9ce0754a2b9d8369d6684

### System Info

```shell
System:
    OS: Linux 6.18 cpe:/o:nixos:nixos:26.05 26.05 (Yarara)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 17.72 GB / 27.23 GB
    Container: Yes
    Shell: 4.2.1 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 22.21.1 - /nix/store/l85fis49agvp5q1ild1rfh4rrgmn92sr-nodejs-22.21.1/bin/node
    npm: 10.9.4 - /nix/store/l85fis49agvp5q1ild1rfh4rrgmn92sr-nodejs-22.21.1/bin/npm
  Browsers:
    Chromium: 143.0.7499.40
    Firefox: 145.0.2
    Firefox Developer Edition: 145.0.2
  npmPackages:
    @vitest/browser-preview: ^4.0.16 => 4.0.16 
    @vitest/ui: latest => 4.0.16 
    vite: latest => 7.3.0 
    vitest: latest => 4.0.16
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Looks like we need the same hack we added here here #6079 or just reuse the tester id.

@sheremet-va added here #8877

**Comment by plusgut** [comment]
@userquin i was thinking about that too, but i was hesitant to do so. Isn`t it problematic to have the same moduleId for several different imports?
I was thinking to just use good ol Math.random instead, this way we would have different ids when wrapModule is called multiple times. What do you think about that?

But if you think that testerId is good enough, i`ll of course adjust my pr.
