### ISSUE TITLE
Vitest v0.32.0 cannot find some module

### ISSUE THREAD

**Issue by nakamurakjr** [vitest-dev/vitest#3586]
### Describe the bug

After updating vitest from v0.31.4 to v0.32.0, import of some files fails.
`Error: Cannot find module '*.svg?.tsx'`

I created my own plug-in (reactSvgr), imported SVG files with an extension like `* .svg?.tsx`, and used it as a React component.
In the latest vitest, it stopped working, probably because they didn't apply the plugin.

This seems to be a regression of the change made from this pull request: https://github.com/vitest-dev/vitest/issues/3307.
While I believe that change was necessary, I am currently facing difficulties due to this regression.

### Reproduction

https://github.com/kazuma1989/vitest-issue-3307

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.53 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
    npm: 9.5.0 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 15.6.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nakamurakjr** [comment]
The bug I described has been fixed by following PRs.
https://github.com/vitest-dev/vitest/pull/3544
https://github.com/vitest-dev/vitest/releases/tag/v0.32.1
