### ISSUE TITLE
Vitest 0.25.1 regression: TypeError: url.match is not a function

### ISSUE THREAD

**Issue by belgattitude** [vitest-dev/vitest#2331]
### Describe the bug

After update to 0.25.0 to 0.25.1 (also present in 0.25.2), the test suite complains with

**TypeError: url.match is not a function**

Can confirm it does not happen in 0.25.0

### Setup: 

- happy-dom: 7.7.0 (latest)
- vite: 3.2.3 (latest)
- config used: https://github.com/belgattitude/nextjs-monorepo-example/blob/e3f1e4d58853538531f5d068a616b21a26088588/apps/nextjs-app/vitest.config.ts

### Investigation

Haven't tried on jsdom, but with happy-dom seems the url is passed as URL object, not a string. As per MDN [it should be a string](https://developer.mozilla.org/en-US/docs/Web/API/URL#constructor). 

![image](https://user-images.githubusercontent.com/259798/201901079-20996ad4-fbd3-4e95-9ac2-b31ac37b5f59.png)

### Reproduce

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git
cd nextjs-monorepo-example
git switch reprod-regression-vitest
yarn install
cd apps/nextjs-app
yarn test-unit
```

### Notes

CI log, see https://github.com/belgattitude/nextjs-monorepo-example/pull/2912

![image](https://user-images.githubusercontent.com/259798/201896798-d790bbb6-e9d2-4df5-a2f8-1bf1c0ad966e.png)

### Reproduction

Sorry I don't have a minimal reprod example yet, but you'll can find a failing PR here:

https://github.com/belgattitude/nextjs-monorepo-example/pull/2912

To install

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git
cd nextjs-monorepo-example
git switch reprod-regression-vitest
yarn install
cd apps/nextjs-app
yarn test-unit
```

It's a monorepo, the app failing is based on nextjs. All deps to latest (happy-dom, vite). Can confirm it does not break with version 0.25.0 

Let me know if I can help to make it easier for you. 

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.74 GB / 15.29 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 4.0.0-rc.28 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by belgattitude** [comment]
@sheremet-va just to mention after reading https://github.com/vitest-dev/vitest/issues/2305. 

This one is not exactly related to https://github.com/capricorn86/happy-dom/issues/569 (the base url parameter) as in the msw issue. That said the fix you've provided works perfectly:

```javascript
// setupVitest
import { URL } from 'node:url';
globalThis.URL = URL;
```

The issue here seems to come from invalid argument: (ie `new URL(new URL("https://xyz"))` rather than `new URL("https://xyz")`. I guess it's not related to vitest, but worth to mention in case you've missed it.

Thanks a lot
