### ISSUE TITLE
vitest 0.24.* breaks StyledComponents

### ISSUE THREAD

**Issue by snailcatcher** [vitest-dev/vitest#2265]
### Describe the bug

With vitest 0.23.4 [styled-components](https://github.com/styled-components/styled-components) work like expected.
After the update to 0.24.5 all testcases which use _styled-components_ break with the exact same error.

```sh
FAIL  src/.../Footer.spec.tsx [ src/.../Footer.spec.tsx ]
TypeError: I.button is not a function
 ❯ ../../lalala/src/dist/lala-shared.es.js:81:17
     79|   desktop: `(min-width: ${yt.desktop})`,
     80|   desktopL: `(min-width: ${yt.desktop})`
     81| }, rn = I.button`
       |                 ^
     82|   display: flex;
     83|   align-items: center;
```

### Reproduction

Footer.styled.ts
```ts
import styled from "styled-components";

export const VersionInfo = styled.div`
  visibility: hidden;
`
```

Footer.tsx
```ts
import {VersionInfo} from "Footer.styled";
import React from "react";

const Footer = () => {
    return <div>
        <VersionInfo>{import.meta.env.VITE_VERSION}</VersionInfo>
    </div>
```

Footer.spec.tsx
```ts
import { render } from "@testing-library/react";
import { describe, test } from 'vitest'
import '@testing-library/jest-dom'
import Footer from './Footer';

describe('Footer', () => {
  test('has created', (context: any) => {
    const rendered = render(<Footer />); // <-- this fails with the error above
  });
})
```

**strange info:**
If I delete the _Footer.styled.ts_ and change the _Footer.tsx_ to
```ts
import {VersionInfo} from "Footer.styled";
import React from "react";
import styled from "styled-components";

export const VersionInfo = styled.div`
  visibility: hidden;
`

const Footer = () => {
    return <div>
        <VersionInfo>{import.meta.env.VITE_VERSION}</VersionInfo>
    </div>
```
then the test in _Footer.spec.tsx_ works fine

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.07 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 16.0
  npmPackages:
    @vitejs/plugin-react: ^2.2.0 => 2.2.0 
    vite: ^3.2.2 => 3.2.2 
    vitest: ^0.24.0 => 0.24.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can you provide a runnable minimal reproduction (stackblitz or git repo)? I can't combine your small peaces into reliable reproduction, you have some env variables, other packages and so on.

**Comment by snailcatcher** [comment]
Sorry for the late answer, I had to look up the real problem myself.
I don't know the exact problem by now, but I was able to fix it.
_styled-components_ was declared as external package in my vite.config under _build.rollupOptions.external_ and was defined it under  _build.rollupOptions.output.globals_ in my library project. 
After removing both of them it seems to work fine. But I don't know what this has to do with the version change.

So there may be still an issue, but I'm not really able to write a reproduction for this.
