### ISSUE TITLE
[0.20.x] vitest no longer works with yarn pnp

### ISSUE THREAD

**Issue by jereklas** [vitest-dev/vitest#1758]
### Describe the bug

After upgrading to 0.20.x, tests are no longer able to run due to yarn being unable to find a module
```
events.js:377
      throw er; // Unhandled 'error' event
      ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/user/git/vitest_yarn2/.yarn/__virtual__/vitest-virtual-3235595f85/0/cache/vitest-npm-0.20.2-9730ec2bf1-eea156689f.zip/node_modules/vitest/dist/loader.mjs' imported from /home/user/git/vitest_yarn2/
Did you mean to import /home/user/git/vitest_yarn2/.yarn/__virtual__/vitest-virtual-3235595f85/0/cache/vitest-npm-0.20.2-9730ec2bf1-eea156689f.zip/node_modules/vitest/dist/loader.mjs?
```

### Reproduction

Here is a repo that exhibits the problem. I purposefully left it in a working state with vitest at 0.19.1, to show that 0.19.1 worked. The README.md has details on how to reproduce.

https://github.com/jereklas/vitest_yarn2

### System Info

```shell
System:
    OS: Linux 5.14 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 465.59 MB / 15.36 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.20.0 - /usr/bin/node
    Yarn: 3.2.2 - /usr/bin/yarn
    npm: 6.14.17 - /usr/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Try disabling `deps.registerNodeLoader` for now

**Comment by jereklas** [comment]
I was just doing that and was about to report back that `deps.registerNodeLoader` is a work around! You beat me to it.

**Comment by sheremet-va** [comment]
It's not possible to use custom experimental loader with Yarn PnP at the moment. We need https://github.com/nodejs/node/pull/43772 to be resolved first.

For now we will detect, if running under Yarn PnP and disable `registerNodeLoader` in #1773.

**Comment by manoldonev** [comment]
Experienced similar issue in a SolidJS project maintained with `pnpm`. Tests worked flawlessly with 0.19.x and started failing with a cryptic `You appear to have multiple instances of Solid. This can lead to unexpected behavior.` in 0.20.x. Workaround to disable `deps.registerNodeLoader` also works in this scenario.

**Comment by sheremet-va** [comment]
> Experienced similar issue in a SolidJS project maintained with `pnpm`. Tests worked flawlessly with 0.19.x and started failing with a cryptic `You appear to have multiple instances of Solid. This can lead to unexpected behavior.` in 0.20.x. Workaround to disable `deps.registerNodeLoader` also works in this scenario.

Solid example was updated, you no longer need to inline solid.
