### ISSUE TITLE
Cannot find module '@vitest/utils/diff' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ocavue** [vitest-dev/vitest#3162]
### Describe the bug

After updating vitest to 0.30.0, running `tsc --noEmit` will raise the following errors:

```
node_modules/@vitest/runner/dist/utils.d.ts:5:29 - error TS2307: Cannot find module '@vitest/utils/diff' or its corresponding type declarations.

5 import { DiffOptions } from '@vitest/utils/diff';
                              ~~~~~~~~~~~~~~~~~~~~

node_modules/vitest/dist/index.d.ts:6:37 - error TS2307: Cannot find module '@vitest/snapshot/environment' or its corresponding type declarations.

6 export { SnapshotEnvironment } from '@vitest/snapshot/environment';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Reproduction

https://codesandbox.io/p/sandbox/practical-darwin-sq0t0x?file=%2Fpackage.json

Run `yarn test` in this repo and you will see the error. 

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/24715727/230839685-530ace0f-1760-4f00-b43a-4ed8d8ae5f38.png">

### System Info

```shell
N/A (Codesandbox environment)
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xieyuheng** [comment]
I meet similar errors when update from 0.29 to 0.30.
