### ISSUE TITLE
Upgrade vitest to work with Typescript 5

### ISSUE THREAD

**Issue by TrevTheDev** [vitest-dev/vitest#2931]
### Clear and concise description of the problem

Firstly thank you for your awesome tool!  Please enhance your awesome tool, to work with Typescript 5.0.  It currently can't compile code that uses the new `const` feature.  I've done a little digging and it seems this is caused by outdated dependencies being used by Vitest.  I tried to upgrade all dependencies and it now half works, however, it breaks something elsewhere.

You are probably already aware of this issue, but I didn't find it, so thought I'd log it - as it's causing me some issues.

### Suggested solution

Upgrade vitest to support Typescript 5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by helmturner** [comment]
Here's a stack trace from my encounter with this issue:

```bash
/src/index.ts:65:2: ERROR: Expected identifier but found "const"
 ❯ failureErrorWithLog node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1604:15
 ❯ node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:837:29
 ❯ responseCallbacks.<computed> node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:701:9
 ❯ handleIncomingPacket node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:756:9
 ❯ Socket.readFromStdout node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:677:7
 ❯ Socket.emit node:events:526:28
 ```

Adding the following to `package.json` works as a temporary fix in my case without causing any issues, as far as I can tell. YMMV, of course.

```
  "overrides": {
    "esbuild": "0.17.5",
    "typescript": "5.0.0-beta"
  }
```

This overrides the version of esbuild and typescript for ALL dependencies. If you just want to update the dependencies for Vitest, use this:

```
  "overrides": {
    "vitest": {
      "esbuild": "0.17.5",
      "typescript": "5.0.0-beta"
    }
  }
```

**Comment by sheremet-va** [comment]
Vitest relies on Vite for code transformations.

**Comment by sapphi-red** [comment]
esbuild 0.17.14 (released yesterday) supports `const` modifier. (Note that esbuild 0.17.x is used from Vite 4.2)
I guess it now works.

**Comment by helmturner** [comment]
Yup, I can confirm that I was able to remove all overrides from my manifest after updating my dependencies. Everything works - this issue can be closed.
