### ISSUE TITLE
During type checking, the type files in vitest and vite cannot find the type they use

### ISSUE THREAD

**Issue by yingpengsha** [vitest-dev/vitest#4921]
### Describe the bug

My type checking use case passed without a hitch, but there was a problem with the type inside the library itself

- log: https://github.com/Blueprint-Breeze/aabb/actions/runs/7460993639/job/20300207519#step:7:50

```shell
⎯⎯⎯⎯⎯⎯ Typecheck Error ⎯⎯⎯⎯⎯⎯⎯
Error: Error: node_modules/.pnpm/@vitest+utils@1.1.3/node_modules/@vitest/utils/dist/error.d.ts(4,58): error TS2304: Cannot find name 'WeakKey'.
Error: node_modules/.pnpm/@vitest+utils@1.1.3/node_modules/@vitest/utils/dist/error.d.ts(6,96): error TS2304: Cannot find name 'WeakKey'.
Error: node_modules/.pnpm/@vitest+utils@1.1.3/node_modules/@vitest/utils/dist/error.d.ts(6,133): error TS2304: Cannot find name 'WeakKey'.
Error: node_modules/.pnpm/vite@5.0.11_@types+node@20.10.6/node_modules/vite/dist/node/index.d.ts(6,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations
```

### Reproduction

- repo: https://github.com/Blueprint-Breeze/aabb
- log: https://github.com/Blueprint-Breeze/aabb/actions/runs/7460993639/job/20300207519#step:7:50

### System Info

```shell
> This is my local environment configuration, of course, can also reproduce the previous problem

  System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 122.00 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.1/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    pnpm: 7.33.6 - ~/.nvm/versions/node/v16.20.1/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 120.0.2210.121
    Safari: 16.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
The issue might related to
- https://github.com/vitest-dev/vitest/issues/4567
- https://github.com/vitejs/vite/discussions/12466#discussioncomment-7596971

Probably your tsconfig is somewhat old-ish compared to what Vite/Vitest expect and having `"moduleResolution": "Bundler"` and `"lib": ["ESNext"]` might be recommended, something like:

https://github.com/vitest-dev/vitest/blob/9ec3f743edfd0a5996a4c6eced35bbf95cf1604e/tsconfig.base.json#L1-L6

Or disabling type check inside dependencies would probably workaround this and somewhat common thing to do as well:

https://github.com/vitest-dev/vitest/blob/ca76f4576d1fbfb82f9131fbefc0e3cabaea4902/tsconfig.base.json#L37

I For some reason, I cannot run your repo locally (somehow Vitest is stuck) so I couldn't verify though. It might be nice if you can minimize repro further.

**Comment by mrazauskas** [comment]
Upgrading TypeScript and running `tsc --noEmit` in the reproduction repo, gives: "Cannot find module 'rollup/parseAst' or its corresponding type declarations." This looks like #4567. Following the thread one can find a workaround in https://github.com/rollup/rollup/issues/5199. As already mentioned, the suggestion is to use `moduleResolution: "bundler"`. I just wanted to make it clear what is the reason here.

`moduleResolution: "bundler"` make `tsc --noEmit` work on TypeScript 5.2.

Running `tsc --noEmit` with TypeScript 5.0 and 5.1 complains that it "Cannot find name 'WeakKey'" in several places of `@vitest/utils`. It is not easy to browse through Typescripts repo, but seems like the `WeakKey` type was add in https://github.com/microsoft/TypeScript/pull/54195. Relatively new.

Does it mean `vitest --typecheck` supports only TypeScript 5.2 and up? And/or requires `moduleResolution: "bundler"`? (By the way, with these changes and also `"skipLibCheck": true` added, it still gets stuck for me in the reproduction repo.)

Should these details be added to Vitests documentation, perhaps?
