### ISSUE TITLE
vi.mock importOriginal causes ERR_MODULE_NOT_FOUND with &v=<hash> suffix appended to path in 4.1.0 (regression from 4.0.x)

### ISSUE THREAD

**Issue by csvan** [vitest-dev/vitest#9887]
## Bug Report

**Vitest version:** 4.1.0
**Regression from:** 4.0.18 (works correctly)
**Environment:** Node 22, happy-dom

### Description

In Vitest 4.1.0, calling `vi.mock` with `importOriginal` (or `vi.importActual`) on a package listed in `test.server.deps.inline` causes `ERR_MODULE_NOT_FOUND`. The module evaluator appends `&v=<hash>` directly to the resolved file path, producing a path that does not exist on disk.

The same error occurs when the package is in `test.deps.optimizer.client.include` — the pre-bundled chunk path also gets the suffix appended.

This is a regression — identical configuration works correctly on 4.0.18.

### Minimal reproduction

```ts
// vitest.config.ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'happy-dom',
    server: {
      deps: {
        inline: ['react-redux'],
      },
    },
  },
});
```

```ts
// some.test.ts
vi.mock('react-redux', async (importOriginal) => ({
  ...(await importOriginal()),
  useSelector: vi.fn(),
}));

test('example', () => {});
```

### Error output

```
Error: [vitest] There was an error when mocking a module.
Caused by: Error: Cannot find module '/node_modules/react-redux/dist/react-redux.mjs&v=c1c7e391'
  { code: 'ERR_MODULE_NOT_FOUND' }
```

The `&v=<hash>` suffix is appended to the literal resolved file path by the module evaluator, making it unresolvable on disk.

When the package is instead added to `test.deps.optimizer.client.include`, the pre-bundled chunk gets the same treatment:

```
Error: Cannot find module '/node_modules/.vite/vitest/.../deps/react-redux.js&v=8f02ed9a'
  { code: 'ERR_MODULE_NOT_FOUND' }
```

### Expected behavior

`importOriginal` / `vi.importActual` should resolve the module correctly regardless of whether it is listed in `server.deps.inline` or `optimizer.client.include`, as it did in 4.0.x.

### Workaround

Pinning to `~4.0.0` via `overrides` in `package.json` resolves the issue.

**Comment by marzelc** [comment]
I have the same problem, if I enable `test.deps.optimizer.client.enable = true` all my `importOriginal()` fails with the same error

**Comment by csvan** [comment]
I'm sorry what? Why not planned? This is an actual regression breaking actual tests, it's not an isolated problem

**Comment by hmkiesel** [comment]
I'm experiencing the same problem with version 4.1.1.

**Comment by csvan** [comment]
Please reopen

**Comment by sheremet-va** [comment]
> Please reopen

Please follow the instructions https://github.com/vitest-dev/vitest/issues/9887#issuecomment-4073198886

**Comment by tngwoerleij** [comment]
A minimal reproduction can be found here: https://stackblitz.com/edit/vitest-dev-vitest-kbm8rpok

According to a lengthy analysis by Claude Sonnet 4.6 via Claude Code revealed that `removeQuery` in https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/runtime/moduleRunner/utils.ts#L17 incorrectly strips "?" when replacing "_vitest_original" causing a broken URL like "/node_modules/react-redux/dist/react-redux.mjs&v=47a14a5f" in the reproduction sample, where "&" would need to be "?". This looks to me as having been introduced with https://github.com/vitest-dev/vitest/commit/1e89ec0205cd6d475056b2b18370a42c21eb9cbd#diff-179d3b9b865e3a3aec3690e8060c93217f9fdc1e8a3da4d5468c976d5d5fc502.

**Comment by tngwoerleij** [comment]
> Please follow the instructions [#9887 (comment)](https://github.com/vitest-dev/vitest/issues/9887#issuecomment-4073198886)

@sheremet-va Could you please reopen the issue based on the now provided minimal reproduction? Thank you 🙂
